const DIFFICULTY = 3;
const MINE_RATE = 3000;
const MINING_REWARD = 50;
const BLOCK_GENERATION_INTERVAL = 5;
const DIFFICULTY_ADJUSTMENT_INTERVAL = 5;

module.exports = {
  DIFFICULTY,
  MINE_RATE,
  MINING_REWARD,
  BLOCK_GENERATION_INTERVAL,
  DIFFICULTY_ADJUSTMENT_INTERVAL
}